

services:
  qdrant:
    image: qdrant/qdrant:dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    restart: unless-stopped

  # embedding-gamma:
  #   # Replace with the actual image for your EmbeddingGamma model
  #   image: your-embedding-gamma-image:latest
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - MODEL_NAME=${EMBEDDING_MODEL_NAME}
  #     - EMBEDDING_DIM=${EMBEDDING_DIM}

# services:
#   ubuntu-bash:
#     image: ubuntu:latest
#     container_name: ubuntu_interactive
#     models:
#       - infer
#     # Override the default command to start bash
#     command: ["/bin/bash"]

# models:
#   infer:
#     model: ai/llama3.2:latest
#     context_size: 32768
#     runtime_flags:
#       - ""
